{{- include "crowdsec-blocklist-import.validateMode" . -}}
{{- if eq .Values.mode "cronjob" -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "crowdsec-blocklist-import.fullname" . }}
  labels:
    {{- include "crowdsec-blocklist-import.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.cronjob.schedule | quote }}
  {{- with .Values.cronjob.timeZone }}
  timeZone: {{ . | quote }}
  {{- end }}
  concurrencyPolicy: {{ .Values.cronjob.concurrencyPolicy }}
  startingDeadlineSeconds: {{ .Values.cronjob.startingDeadlineSeconds }}
  successfulJobsHistoryLimit: {{ .Values.cronjob.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cronjob.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      backoffLimit: {{ .Values.cronjob.backoffLimit }}
      activeDeadlineSeconds: {{ .Values.cronjob.activeDeadlineSeconds }}
      template:
        metadata:
          labels:
            {{- include "crowdsec-blocklist-import.selectorLabels" . | nindent 12 }}
          {{- with .Values.podLabels }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.podAnnotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        spec:
          serviceAccountName: {{ include "crowdsec-blocklist-import.serviceAccountName" . }}
          automountServiceAccountToken: {{ .Values.serviceAccount.automountToken }}
          restartPolicy: {{ .Values.cronjob.restartPolicy }}
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.podSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
            - {{- include "crowdsec-blocklist-import.container" (dict "root" . "interval" "0") | nindent 14 }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
